### ISSUE TITLE
Navigation with Ctrl+n/p

### ISSUE THREAD

**Issue by dlvhdr** [SKalt/git-cc#33]
In addition to up/down

**Comment by SKalt** [comment]
since j and k are both valid letters, implementing j/k navigation would require adding a navigation mode that's distinct from the current default prefix-search mode. I'm unwilling to do that, but I'd accept a PR with an appropriate change as long as all commits in the PR have a DCO. I know the devs at Charmbracelet recently updated their default helpbar and list-navigation components in the bubbles repo, so reviewing those would be a good place to start.

**Comment by dlvhdr** [comment]
Oh yeah... how about ctrl+n/p? That's standard in vim as well, also fzf

**Comment by SKalt** [comment]
Key combos wouldnt add as much complexity as full-on modal navigation! I'll
put this issue on my agenda.

**Comment by SKalt** [comment]
If you install the most recent version (0.0.16), the ctrl+p/ctrl+n functionality should be present.
